### ISSUE TITLE
Alacritty not found

### ISSUE THREAD

**Issue by neomoth** [exequtic/apdatifier#109]
Exactly what is says on the tin.

I have Alacritty installed, and the box for selecting a terminal is empty despite Alacritty being a supported terminal.
Just to verify that the dropdown box works at all, I installed kitty and it is able to locate kitty just fine.
![Image](https://github.com/user-attachments/assets/bfabb997-8f65-416b-a1e4-c4d691cdbc0f)
^ image showing the dropdown lacking an option for alacritty.
I have attempted to restart my pc, uninstall and reinstall both apdatifier and alacritty, nothing seems to work.

**Comment by neomoth** [comment]
Turns out the the latest release isn't up-to-date with the README, my mistake.

**Comment by exequtic** [comment]
This was fixed in commit dac802e16abe871a6815a4dfc4589e0671ff2bd8.
Install Development version (Settings -> General -> Misc)

**Comment by neomoth** [comment]
I just now saw this comment, I tried to install the development version through the settings but it seemingly does nothing?
I even tried restarting plasmashell as is suggested on the README as well as restarting my computer, but it still appears to be using the stable release as I still cannot select alacritty.

**Comment by exequtic** [comment]
> I tried to install the development version through the settings but it seemingly does nothing?

You can try updating directly by running the script in any terminal:
`~/.local/share/plasma/plasmoids/com.github.exequtic.apdatifier/contents/tools/sh/utils installDev`
